[package]
name = "sky_native_adapters"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde_json = "1"
sky_app_core = { path = "../sky_app_core" }
sky_player = { path = "../sky_player" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "=0.61.2", features = [
    "Win32_Storage_FileSystem",
] }
