from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest


def _load_build_module() -> ModuleType:
    path = Path(__file__).parents[1] / "scripts" / "build_rust_wheel.py"
    spec = importlib.util.spec_from_file_location("build_rust_wheel_under_test", path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


BUILD = _load_build_module()


def test_build_commit_requires_clean_matching_checkout(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(BUILD, "git_head", lambda repo_root: "head-commit")
    monkeypatch.setattr(BUILD, "git_status", lambda repo_root: "")
    monkeypatch.setenv("GITHUB_SHA", "stale-commit")

    with pytest.raises(RuntimeError, match="does not match checkout HEAD"):
        BUILD.expected_build_commit(Path("."))


def test_dirty_development_build_is_explicitly_marked(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(BUILD, "git_head", lambda repo_root: "head-commit")
    monkeypatch.setattr(BUILD, "git_status", lambda repo_root: " M source.rs")
    monkeypatch.setenv("GITHUB_SHA", "stale-commit")

    assert (
        BUILD.expected_build_commit(Path("."), allow_dirty=True)
        == "head-commit-dirty"
    )


def test_clean_matching_sha_returns_head(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(BUILD, "git_head", lambda repo_root: "head-commit")
    monkeypatch.setattr(BUILD, "git_status", lambda repo_root: "")
    monkeypatch.setenv("GITHUB_SHA", "head-commit")

    assert BUILD.expected_build_commit(Path(".")) == "head-commit"


def test_clean_without_reported_sha_returns_head(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(BUILD, "git_head", lambda repo_root: "head-commit")
    monkeypatch.setattr(BUILD, "git_status", lambda repo_root: "")
    monkeypatch.delenv("GITHUB_SHA", raising=False)

    assert BUILD.expected_build_commit(Path(".")) == "head-commit"


def test_application_build_metadata_contains_only_full_build_commit(tmp_path: Path) -> None:
    package = tmp_path / "src" / "sky_music"
    package.mkdir(parents=True)

    path = BUILD.generate_application_build_metadata(tmp_path, "a" * 40)

    assert path.read_text(encoding="utf-8") == (
        "# Auto-generated by build_rust_wheel.py — do not edit manually.\n"
        f'APP_BUILD_COMMIT: str = "{"a" * 40}"\n'
    )


def test_dirty_release_build_is_rejected(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(BUILD, "git_head", lambda repo_root: "head-commit")
    monkeypatch.setattr(BUILD, "git_status", lambda repo_root: "?? new.rs")
    monkeypatch.delenv("GITHUB_SHA", raising=False)

    with pytest.raises(RuntimeError, match="requires a clean working tree"):
        BUILD.expected_build_commit(Path("."))


def test_main_returns_failure_when_provenance_gate_fails(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(BUILD, "expected_build_commit", lambda *args, **kwargs: (_ for _ in ()).throw(RuntimeError("stale")))
    monkeypatch.setattr(sys, "argv", ["build_rust_wheel.py"])

    assert BUILD.main() == 1
