"""Tests for the single-source version resolution contract.

The runtime version is consumed by the update checker (for ``is_newer``
comparisons) and by the UI app bar. A stale or mismatched fallback (e.g. a
hardcoded ``"2.3.0"`` literal left over from an earlier release) silently
produces wrong update decisions — either suppressing real updates or, worse,
prompting the user to "update" to the version they already have.

These tests pin the resolution order:

1. ``sky_music._version.__version__`` (auto-generated by ``build_app.py``)
2. ``importlib.metadata.version("sky-player")``
3. ``"0.0.0-dev"`` sentinel — safe degradation that compares as older than
   every real release, so it surfaces an update prompt rather than hiding one.
"""

from __future__ import annotations

import builtins
import importlib.metadata
import sys
import tomllib
from collections.abc import Mapping, Sequence
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
_PYPROJECT = _REPO_ROOT / "pyproject.toml"


def _pyproject_version() -> str:
    with _PYPROJECT.open("rb") as f:
        data = tomllib.load(f)
    return data["project"]["version"]


def test_pyproject_version_is_pep440() -> None:
    from packaging.version import Version

    Version(_pyproject_version())  # raises InvalidVersion if not parseable


def test_version_module_matches_pyproject() -> None:
    """``_version.py`` is auto-generated from ``pyproject.toml`` — keep in
    sync so frozen builds stamp the canonical version on the Windows exe."""
    from sky_music import _version  # type: ignore[import-not-found]

    assert _version.__version__ == _pyproject_version()


def test_runtime_version_prefers_version_module() -> None:
    """When ``_version.py`` is importable it wins over ``importlib.metadata``.

    This guarantees frozen builds (which always have ``_version.py`` baked in)
    never fall back to dist-info probing even if the latter happens to be
    available, removing a class of version-drift bugs.
    """
    from sky_music import __version__

    canonical = _pyproject_version()
    assert __version__ == canonical, (
        f"runtime version {__version__!r} != pyproject {canonical!r}"
    )


def test_fallback_to_metadata_when_version_module_missing(monkeypatch: pytest.MonkeyPatch) -> None:
    """If ``_version.py`` is absent, fall back to ``importlib.metadata`` —
    never to a stale hardcoded literal."""
    import sky_music

    # Simulate an absent ``_version.py`` by removing it from the module
    # cache and rejecting re-imports of that submodule.
    monkeypatch.delitem(sys.modules, "sky_music._version", raising=False)

    original_import = builtins.__import__

    def _hide_version_submodule(
        name: str,
        globals: Mapping[str, object] | None = None,
        locals: Mapping[str, object] | None = None,
        fromlist: Sequence[str] | None = None,
        level: int = 0,
    ) -> object:
        if name == "sky_music._version":
            raise ImportError("simulated absent _version.py")
        return original_import(name, globals, locals, fromlist, level)

    monkeypatch.setattr(builtins, "__import__", _hide_version_submodule)
    monkeypatch.setattr(importlib.metadata, "version", lambda _n: "9.9.9-meta")

    # Drop the cached reference so _resolve_version runs again.
    monkeypatch.setattr(sky_music, "__version__", sky_music._resolve_version())
    assert sky_music.__version__ == "9.9.9-meta"


def test_dev_sentinel_when_neither_source_available(monkeypatch: pytest.MonkeyPatch) -> None:
    """Bare checkout without dist-info must degrade to ``0.0.0-dev`` — which
    every real release compares strictly greater than, so the user is prompted
    to install a real build rather than silently having updates suppressed."""
    import sky_music

    monkeypatch.delitem(sys.modules, "sky_music._version", raising=False)

    original_import = builtins.__import__

    def _hide_version_submodule(
        name: str,
        globals: Mapping[str, object] | None = None,
        locals: Mapping[str, object] | None = None,
        fromlist: Sequence[str] | None = None,
        level: int = 0,
    ) -> object:
        if name == "sky_music._version":
            raise ImportError("simulated absent _version.py")
        return original_import(name, globals, locals, fromlist, level)

    monkeypatch.setattr(builtins, "__import__", _hide_version_submodule)

    def _raise_not_found(_name: str) -> str:
        raise importlib.metadata.PackageNotFoundError("sky-player")

    monkeypatch.setattr(importlib.metadata, "version", _raise_not_found)

    monkeypatch.setattr(sky_music, "__version__", sky_music._resolve_version())
    assert sky_music.__version__ == "0.0.0-dev"


def test_dev_sentinel_compares_as_older_than_any_release() -> None:
    from sky_music.domain.update_checker import is_newer

    assert is_newer("0.0.1", "0.0.0-dev") is True
    assert is_newer("2.3.3", "0.0.0-dev") is True
