use sky_dispatch_win32::input::ReleaseAllOutcome;
use std::collections::HashMap;

/// Public snapshot shape returned by
/// [`crate::engine::NativeDispatchSession::snapshot`].
#[derive(Debug, Clone)]
pub struct EngineSnapshot {
    pub elapsed_us: u64,
    pub total_us: u64,
    pub lateness_us: u64,
    pub max_lateness_us: u64,
    pub late_2ms: u64,
    pub late_5ms: u64,
    pub late_10ms: u64,
    pub release_max_us: u64,
    pub release_late_2ms: u64,
    pub recent_latencies_us: Vec<i64>,
    pub is_running: bool,
    pub is_finished: bool,
    pub is_paused: bool,
    pub status: String,
    pub active_count: usize,
    pub possibly_active_count: usize,
    pub failed_release_count: usize,
    pub last_error: Option<String>,
    pub keys_dropped: u64,
    pub chord_split_events: u64,
    pub sendinput_partial_events: u64,
    pub sendinput_zero_progress_failures: u64,
    pub chords_rejected: u64,
    pub chord_integrity_lost: u64,
    pub authored_conflict_events: u64,
    pub authored_chords_rejected: u64,
    pub authored_keys_rejected: u64,
    pub keys_inserted_before_failure: u64,
    pub keys_rolled_back: u64,
    pub rollback_residue_keys: u64,
    pub lead_saturation_count_down: Vec<u64>,
    pub lead_saturation_count_up: Vec<u64>,
    pub positive_residual_at_cap: u64,
    pub recovered_zero_progress_but_late: u64,
    pub recovered_zero_progress_retries: u64,
    pub recovered_partial_up_retries: u64,
    pub outcome: Option<String>,
    pub rt_priority_acquired: String,
    pub effective_spin_threshold_us: u64,
    pub wake_error_p50_us: u64,
    pub wake_error_p95_us: u64,
    pub wake_error_p99_us: u64,
    pub wake_error_max_us: u64,
    pub spin_time_us: u64,
    pub playback_wall_time_us: u64,
    pub spin_duty_cycle_ppm: u64,
    pub worker_cpu_time_us: u64,
    pub process_cpu_time_us: u64,
    pub wait_strategy_acquired: String,
    pub power_throttling_disabled: bool,
    pub input_path_degraded: bool,
    pub sendinput_path_degraded: bool,
    pub core_post_send_degraded: bool,
    pub observer_degraded: bool,
    pub wait_path_degraded: bool,
    pub sendinput_warn_threshold_us: u64,
    pub core_post_send_warn_threshold_us: u64,
    pub observer_warn_threshold_us: u64,
    pub wait_warn_threshold_us: u64,
    pub sendinput_degraded_samples: u64,
    pub core_post_send_degraded_samples: u64,
    pub observer_degraded_samples: u64,
    pub wait_degraded_samples: u64,
    pub wait_backend_failures: u64,
    pub wait_clock_failures: u64,
    pub wait_interrupted_count: u64,
    pub sendinput_window_bad_count: u64,
    pub core_post_send_window_bad_count: u64,
    pub observer_window_bad_count: u64,
    pub wait_window_bad_count: u64,
    pub sendinput_window_sample_count: u64,
    pub core_post_send_window_sample_count: u64,
    pub observer_window_sample_count: u64,
    pub wait_window_sample_count: u64,
    pub timeline_rebase_count: u64,
    pub timeline_rebase_total_us: u64,
    pub timeline_rebase_max_us: u64,
    pub timeline_rebase_last_reason: Option<String>,
    pub dispatch_occupancy_max_us: u64,
    pub send_down_degraded_samples: u64,
    pub send_up_degraded_samples: u64,
    pub send_mixed_degraded_samples: u64,
    pub send_down_warn_threshold_us: u64,
    pub send_up_warn_threshold_us: u64,
    pub send_mixed_warn_threshold_us: u64,
    pub wait_target_error_us: u64,
    pub idle_wake_count: u64,
    /// Typed `dispatch_ready - sender_completed` peak (§8.13).
    pub core_post_send_max_us: u64,
    /// Peak QPC duration from a blocking deadline wake to the next
    /// `SendInput` call entry (§8.13).
    pub wake_to_send_max_us: u64,
    /// Peak deferred-observer drain duration (§8.13).
    pub observer_duration_max_us: u64,
    /// Observations dropped by the fixed queue's drop-oldest policy (§8.13).
    pub observer_dropped_samples: u64,
    /// High-watermark of the fixed observer queue (§8.13).
    pub observer_queue_high_watermark: u64,
    pub terminal_error: Option<String>,
    pub secondary_errors: Vec<String>,
    pub generation_count: u64,
    pub generation_status_counts: HashMap<String, u64>,
    pub abort_counts_by_reason: HashMap<String, u64>,
    pub release_outcome: Option<ReleaseAllOutcome>,
    pub startup_ready: bool,
    pub startup_latency_us: Option<u64>,
}

/// Allocation-light frequent polling shape. It deliberately excludes final
/// report maps, release provenance, estimator output, and build metadata.
#[derive(Debug, Clone)]
pub struct EngineProgressSnapshot {
    pub elapsed_us: u64,
    pub total_us: u64,
    pub max_lateness_us: u64,
    pub late_2ms: u64,
    pub late_5ms: u64,
    pub late_10ms: u64,
    pub release_max_us: u64,
    pub release_late_2ms: u64,
    pub recent_latencies_us: Vec<i64>,
    pub is_running: bool,
    pub is_finished: bool,
    pub is_paused: bool,
    pub status: String,
    pub has_terminal_error: bool,
    pub active_count: usize,
    pub possibly_active_count: usize,
    pub failed_release_count: usize,
    pub last_error: Option<String>,
    pub keys_dropped: u64,
    pub chord_split_events: u64,
    pub sendinput_partial_events: u64,
    pub sendinput_zero_progress_failures: u64,
    pub chords_rejected: u64,
    pub authored_conflict_events: u64,
    pub authored_chords_rejected: u64,
    pub authored_keys_rejected: u64,
    pub keys_inserted_before_failure: u64,
    pub keys_rolled_back: u64,
    pub rollback_residue_keys: u64,
    pub input_path_degraded: bool,
    pub sendinput_path_degraded: bool,
    pub core_post_send_degraded: bool,
    pub observer_degraded: bool,
    pub wait_path_degraded: bool,
    pub sendinput_warn_threshold_us: u64,
    pub core_post_send_warn_threshold_us: u64,
    pub observer_warn_threshold_us: u64,
    pub wait_warn_threshold_us: u64,
    pub sendinput_degraded_samples: u64,
    pub core_post_send_degraded_samples: u64,
    pub observer_degraded_samples: u64,
    pub wait_degraded_samples: u64,
    pub wait_backend_failures: u64,
    pub wait_clock_failures: u64,
    pub wait_interrupted_count: u64,
    pub sendinput_window_bad_count: u64,
    pub core_post_send_window_bad_count: u64,
    pub observer_window_bad_count: u64,
    pub wait_window_bad_count: u64,
    pub sendinput_window_sample_count: u64,
    pub core_post_send_window_sample_count: u64,
    pub observer_window_sample_count: u64,
    pub wait_window_sample_count: u64,
    pub timeline_rebase_count: u64,
    pub timeline_rebase_total_us: u64,
    pub timeline_rebase_max_us: u64,
    pub core_post_send_max_us: u64,
    pub wake_to_send_max_us: u64,
    pub observer_duration_max_us: u64,
    pub observer_dropped_samples: u64,
    pub observer_queue_high_watermark: u64,
    pub dispatch_occupancy_max_us: u64,
    pub recovered_zero_progress_but_late: u64,
    pub recovered_zero_progress_retries: u64,
    pub recovered_partial_up_retries: u64,
}
