# pyright: reportMissingImports=false
"""Sky Auto Player package.

Single source of truth for the runtime version string.

Resolution order:
  1. ``sky_music._version.__version__`` — auto-generated by ``build_app.py`` at
     every build; present in both source runs (when the file exists) and frozen
     PyInstaller builds (where ``dist-info`` is not always collected).
  2. ``importlib.metadata.version("sky-auto-player")`` — works for editable/pip
     installs where dist-info is available but ``_version.py`` may not exist.
  3. ``"0.0.0-dev"`` — sentinel for bare checkouts without metadata; makes
     every release compare as newer (safe degradation: prompts the user to
     install a real build rather than silently suppressing updates).

``importlib.metadata`` is imported inside the fallback branch only: its
import chain (zipfile/shutil/bz2) is measurable on every launch, and both
frozen builds and post-build source checkouts resolve via ``_version.py``
without ever reaching the fallback.
"""

from __future__ import annotations

__all__ = ["__version__"]

_DEV_SENTINEL = "0.0.0-dev"


def _resolve_version() -> str:
    try:
        from sky_music._version import (
            __version__ as _v,  # type: ignore[import-not-found]
        )
        if isinstance(_v, str) and _v:
            return _v
    except ImportError:
        pass
    import importlib.metadata

    try:
        return importlib.metadata.version("sky-auto-player")
    except Exception:
        return _DEV_SENTINEL


__version__: str = _resolve_version()
