"""Sky Music Player package.

Single source of truth for the runtime version string.

Resolution order:
  1. ``sky_music._version.__version__`` — auto-generated by ``build_app.py`` at
     every build; present in both source runs (when the file exists) and frozen
     PyInstaller builds (where ``dist-info`` is not always collected).
  2. ``importlib.metadata.version("sky-player")`` — works for editable/pip
     installs where dist-info is available but ``_version.py`` may not exist.
  3. ``"0.0.0-dev"`` — sentinel for bare checkouts without metadata; makes
     every release compare as newer (safe degradation: prompts the user to
     install a real build rather than silently suppressing updates).
"""

from __future__ import annotations

import importlib.metadata

__all__ = ["__version__"]

_DEV_SENTINEL = "0.0.0-dev"


def _resolve_version() -> str:
    try:
        # fmt: off
        from sky_music._version import __version__ as _v  # type: ignore  # pyright: ignore[reportMissingImports]
        # fmt: on
        if isinstance(_v, str) and _v:
            return _v
    except ImportError:
        pass
    try:
        return importlib.metadata.version("sky-player")
    except Exception:
        return _DEV_SENTINEL


__version__: str = _resolve_version()
