"""Windows-side self-update installer.

This module performs the concrete steps of downloading and verifying
an update of Sky Player itself. It isolates all OS-specific code here
behind small, testable functions:

1. ``download_zip`` — stream a release zip into a temp file.
2. ``extract_zip`` — unzip into a staging directory.
3. ``verify_sha256`` / ``compute_sha256``/ ``parse_sha256_sidecar`` — verify a
   downloaded file's SHA256 against a checksum asset (either bare hash or the
   standard Coreutils ``<hash>  <filename>`` sidecar form).

Security notes
--------------
- HTTPS is mandatory for downloads; HTTP URLs are rejected to mitigate MITM.
- SHA256 verification guards the downloaded zip against transport corruption
  or donor tampering; if the sidecar is missing or mismatches, the caller is
  expected to refuse the update.
"""

from __future__ import annotations

import hashlib
import re
import sys
import uuid
import zipfile
from collections.abc import Callable
from pathlib import Path
from typing import Any
from urllib.request import Request, urlopen

# Default chunk size for streaming downloads. 64 KiB balances syscall overhead
# against memory pressure under free-threaded CPython.
_DOWNLOAD_CHUNK: int = 64 * 1024
_HASH_CHUNK: int = 65536


class UpdateInstallerError(RuntimeError):
    """Raised for unrecoverable install-side errors."""


def _urlopen_default(url: str | Request, *, timeout: float) -> Any:
    if isinstance(url, str):
        url = Request(url, headers={"User-Agent": "sky-player-update-installer"})
    return urlopen(url, timeout=timeout)


def download_zip(
    url: str,
    *,
    dest_dir: Path,
    timeout: float = 30.0,
    progress: Callable[[int, int | None], None] | None = None,
    opener: Callable[[str], Any] | None = None,
) -> Path:
    """Download ``url`` to ``dest_dir/sky-update-{uuid}.zip`` and return the path.

    Streaming download never holds the whole file in memory. ``progress`` is
    optional and called as ``progress(bytes_downloaded, total_or_None)``; total
    is read from the ``Content-Length`` header when present.

    Validates inputs strictly:
    - ``url`` must be an ``https://`` URL (reject plain HTTP to mitigate MITM).
    - ``dest_dir`` must exist and be a directory.
    """
    if not isinstance(url, str) or not url.lower().startswith("https://"):
        raise UpdateInstallerError(f"refusing non-https url: {url!r}")
    if not dest_dir.exists() or not dest_dir.is_dir():
        raise UpdateInstallerError(f"destination is not a directory: {dest_dir}")

    open_url = opener if opener is not None else _urlopen_default
    try:
        with open_url(url, timeout=timeout) as response:  # type: ignore[arg-type]
            total: int | None = None
            length_raw = response.headers.get("Content-Length")  # type: ignore[union-attr]
            if isinstance(length_raw, str) and length_raw.isdigit():
                total = int(length_raw)
            dest = dest_dir / f"sky-update-{uuid.uuid4().hex}.zip"
            downloaded = 0
            with dest.open("wb") as f:
                while True:
                    chunk = response.read(_DOWNLOAD_CHUNK)  # type: ignore[union-attr]
                    if not chunk:
                        break
                    f.write(chunk)
                    downloaded += len(chunk)
                    if progress is not None:
                        progress(downloaded, total)
            return dest
    except UpdateInstallerError:
        raise
    except Exception as exc:
        raise UpdateInstallerError(f"download failed: {exc}") from exc


def compute_sha256(path: Path) -> str:
    """Return lowercase-hex SHA256 of ``path``."""
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            buf = f.read(_HASH_CHUNK)
            if not buf:
                break
            h.update(buf)
    return h.hexdigest()


def verify_sha256(file_path: Path, expected_sha256: str) -> bool:
    """True iff SHA256 of ``file_path`` equals ``expected_sha256`` (case-insensitive)."""
    if not file_path.exists():
        return False
    if not isinstance(expected_sha256, str) or not expected_sha256:
        return False
    actual = compute_sha256(file_path)
    return actual.lower() == expected_sha256.strip().lower()


_SHA256_LINE_RE = re.compile(
    r"^\s*([0-9a-fA-F]{64})\s+\*?[^\r\n]*$",
    re.MULTILINE,
)


def parse_sha256_sidecar(text: str) -> str | None:
    """Parse a SHA256 checksum sidecar text blob.

    Accepts both a bare hash on one line and the standard Coreutils form
    ``<hash>  <filename>`` (matching ``.sha256`` files generated by
    ``Get-FileHash`` or ``shasum -a 256``).
    """
    if not isinstance(text, str) or not text.strip():
        return None
    first_line = text.strip().splitlines()[0]
    bare = first_line.strip().split()[0] if first_line.strip() else ""
    if len(bare) == 64 and all(c in "0123456789abcdefABCDEF" for c in bare):
        return bare.lower()
    m = _SHA256_LINE_RE.search(text)
    if m:
        return m.group(1).lower()
    return None


def extract_zip(zip_path: Path, dest_dir: Path) -> Path:
    """Extract ``zip_path`` into ``dest_dir/`` (created if missing) and return ``dest_dir``.

    Safeguards:
    - Refuses entries with absolute paths or ``..`` to avoid zip-slip.
    - Reports a single exception with the offending entry name.
    """
    if not zip_path.exists():
        raise UpdateInstallerError(f"missing zip: {zip_path}")
    dest_dir.mkdir(parents=True, exist_ok=True)
    base = dest_dir.resolve()
    with zipfile.ZipFile(zip_path) as zf:
        for info in zf.infolist():
            if info.is_dir():
                continue
            target = (dest_dir / info.filename).resolve()
            if base != target and base not in target.parents:
                raise UpdateInstallerError(f"zip-slip blocked: {info.filename!r}")
        zf.extractall(dest_dir)
    return dest_dir


def fetch_sha256_sidecar(
    sha256_url: str,
    *,
    timeout: float = 10.0,
    opener: Callable[[str], Any] | None = None,
) -> str | None:
    """Fetch and parse a SHA256 checksum sidecar URL.

    Returns the hex digest (lowercase) or ``None`` if not parseable / missing.
    """
    if not sha256_url:
        return None
    open_url = opener if opener is not None else _urlopen_default
    try:
        with open_url(sha256_url, timeout=timeout) as response:  # type: ignore[arg-type]
            raw = response.read()
    except Exception:
        return None
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return None
    return parse_sha256_sidecar(text)





def install_dir_for_frozen() -> Path:
    """The Sky Player install root: parent of the running exe when frozen.

    Under PyInstaller ``--onedir`` (used here, see ``Sky-Player.spec:97-99``),
    ``sys.executable`` is the launcher exe directly inside the install root.
    Fails with a helpful error if invoked outside a frozen build.
    """
    if not getattr(sys, "frozen", False):
        raise UpdateInstallerError("install_dir_for_frozen only meaningful in frozen builds")
    return Path(sys.executable).resolve().parent
