import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tomllib
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "pyproject.toml").exists() and (candidate / "Sky-Player.spec").exists():
            return candidate
    raise RuntimeError("Cannot locate project root. Run build-app from the source checkout.")

PROJECT_ROOT = find_project_root(Path(__file__).resolve())

SPEC_FILE = PROJECT_ROOT / "Sky-Player.spec"
VERSION_FILE = PROJECT_ROOT / "windows_version_info.txt"
DIST_DIR = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build"

APP_NAME = "Sky-Player"
REQUIRED_ASSETS = ("config.json", "songs")
REQUIRED_UPDATER_ASSETS = ("updater.bat", "installer")
OPTIONAL_ASSETS = ("README.md",)

VERSION_PY = PROJECT_ROOT / "src" / "sky_music" / "_version.py"

def generate_version_py(version: str) -> None:
    """Write the current version into ``_version.py`` so frozen builds
    have a reliable version string that does not depend on ``importlib.metadata``.
    """
    VERSION_PY.write_text(
        f'# Auto-generated by build_app.py — do not edit manually.\n'
        f'__version__: str = "{version}"\n',
        encoding="utf-8",
    )

def get_project_version() -> str:
    path = PROJECT_ROOT / "pyproject.toml"
    try:
        with path.open("rb") as f:
            data = tomllib.load(f)
    except Exception as exc:
        raise RuntimeError(f"Cannot read {path}") from exc

    version = data.get("project", {}).get("version")
    if not isinstance(version, str) or not version.strip():
        raise RuntimeError("Missing or invalid [project].version in pyproject.toml")

    return version.strip()

def windows_version_tuple(version: str) -> tuple[int, int, int, int]:
    parts = [int(x) for x in re.findall(r"\d+", version)[:4]]
    while len(parts) < 4:
        parts.append(0)
    p0, p1, p2, p3 = ([*parts, 0, 0, 0, 0])[:4]
    return (p0, p1, p2, p3)

def generate_version_info(version: str) -> None:
    v_tuple = windows_version_tuple(version)
    v_str = version
    year = datetime.now(UTC).year

    content = f"""
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v_tuple},
    prodvers={v_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'Sky Player Team'),
          StringStruct('FileDescription', 'Sky Music Player for Windows'),
          StringStruct('FileVersion', '{v_str}'),
          StringStruct('InternalName', '{APP_NAME}'),
          StringStruct('LegalCopyright', 'Copyright (c) {year}'),
          StringStruct('OriginalFilename', '{APP_NAME}.exe'),
          StringStruct('ProductName', 'Sky Player'),
          StringStruct('ProductVersion', '{v_str}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    VERSION_FILE.write_text(content.strip(), encoding="utf-8")

def copy_asset(
    src: Path,
    dst: Path,
    ignore: Callable[[str, list[str]], set[str]] | None = None,
) -> None:
    if dst.exists():
        if dst.is_dir():
            shutil.rmtree(dst)
        else:
            dst.unlink()

    if src.is_dir():
        # `ignore` is a callable returned by shutil.ignore_patterns(...). We
        # use it to exclude the installer/Tests/ subtree and stale
        # TestResults.xml from releases — those are dev-only artifacts and
        # bloat the zip (the Tests/ subtree also leaks machine name / user /
        # OS via the committed TestResults.xml).
        shutil.copytree(src, dst, ignore=ignore)
    else:
        shutil.copy2(src, dst)

def run_smoke_test(exe_path: Path) -> bool:
    exe_path = exe_path.resolve()
    if not exe_path.exists():
        print(f"[!] Missing executable: {exe_path}")
        return False

    print(f"[+] Running Smoke Test: {exe_path} --selftest-textual")
    try:
        result = subprocess.run(
            [str(exe_path), "--selftest-textual"],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=str(exe_path.parent),
        )
    except Exception as exc:
        print(f"[!] Error while running Smoke Test: {exc}")
        return False

    if result.returncode == 0:
        print("[v] Smoke Test SUCCEEDED.")
        return True

    print("[!] Smoke Test FAILED!")
    print(result.stderr or result.stdout)
    return False


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def write_release_manifest(release_dir: Path, version: str, exe_name: str, git_head: str) -> None:
    exclude = {"_smoke_test.log", exe_name, "MANIFEST.json"}
    files = []
    for p in sorted(release_dir.rglob("*")):
        if p.is_file() and p.name not in exclude:
            try:
                rel = str(p.relative_to(release_dir)).replace("\\", "/")
                files.append({
                    "path": rel,
                    "size": p.stat().st_size,
                    "sha256": _hash_file(p),
                })
            except (OSError, ValueError):
                pass

    manifest = {
        "app": APP_NAME,
        "version": version,
        "executable": exe_name,
        "executable_sha256": _hash_file(release_dir / exe_name),
        "interpreter": {
            "implementation": sys.implementation.name,
            "version": sys.version.split()[0],
            "freethreaded": not sys._is_gil_enabled(),
        },
        "platform": sys.platform,
        "git_head": git_head,
        "build_time_utc": datetime.now(UTC).isoformat(timespec="seconds"),
        "files": files,
    }
    out = release_dir / "MANIFEST.json"
    out.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"[+] Manifest: {release_dir.name}/{out.name}")


def kill_hanging_selftest(release_dir: Path) -> None:
    """Attempt to force kill any lingering smoke test processes from our specific release dir."""
    if not release_dir.exists():
        return

    release_root = str(release_dir.resolve()).replace("'", "''")
    ps = f"""
    Get-CimInstance Win32_Process |
      Where-Object {{
        $_.Name -eq '{APP_NAME}.exe' -and
        $_.ExecutablePath -like '{release_root}\\*'
      }} |
      ForEach-Object {{
        Stop-Process -Id $_.ProcessId -Force
      }}
    """
    try:
        subprocess.run(
            ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps],
            capture_output=True,
            text=True,
        )
        import time
        time.sleep(1) # Give OS time to release file handles
    except Exception:
        pass

def main() -> None:
    if sys.platform != "win32":
        raise SystemExit("[!] Error: This project only supports building on Windows.")

    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-test", action="store_true")
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Reuse PyInstaller analysis cache for inner-loop. "
             "Never use for release builds.",
    )
    parser.add_argument(
        "--manifest",
        action="store_true",
        help="Generate MANIFEST.json with SHA256 hashes for every "
             "file in the release directory.",
    )
    args = parser.parse_args()

    version = get_project_version()
    print(f"=== Sky Player Build Pipeline v{version} ===")

    generate_version_py(version)
    generate_version_info(version)

    release_dir = DIST_DIR / f"{APP_NAME}-v{version}"
    kill_hanging_selftest(release_dir)

    if not args.no_clean and BUILD_DIR.exists():
        try:
            shutil.rmtree(BUILD_DIR)
        except PermissionError as e:
            print(f"[!] Error cleaning BUILD_DIR: {e}. Attempting to continue...")

    if not args.no_clean and DIST_DIR.exists():
        try:
            shutil.rmtree(DIST_DIR)
        except PermissionError as e:
            raise SystemExit(f"[!] Error cleaning DIST_DIR: {e}.\nFix: close any CMD/Explorer windows currently open in {DIST_DIR} and try again.") from e

    print("[+] Starting PyInstaller...")
    clean_flag = [] if args.no_clean else ["--clean"]
    subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--noconfirm", *clean_flag, str(SPEC_FILE)],
        check=True,
        cwd=str(PROJECT_ROOT),
    )

    raw_dist = DIST_DIR / APP_NAME

    if not raw_dist.exists():
        raise RuntimeError(f"PyInstaller output missing: {raw_dist}")

    print(f"[+] Moving artifact to {release_dir.name}...")
    if release_dir.exists():
        shutil.rmtree(release_dir)
    shutil.move(str(raw_dist), str(release_dir))

    print("[+] Copying assets...")
    for asset in REQUIRED_ASSETS:
        src = PROJECT_ROOT / asset
        if not src.exists():
            raise FileNotFoundError(f"Required asset missing: {src}")
        copy_asset(src, release_dir / asset)

    for asset in OPTIONAL_ASSETS:
        src = PROJECT_ROOT / asset
        if src.exists():
            copy_asset(src, release_dir / asset)

    print("[+] Copying updater assets...")
    # Exclude dev-only artifacts from the installer/ tree shipped with the
    # release: the Pester Tests/ subtree and stale TestResults.xml bloat the
    # zip and leak the previous build's machine/user identifiers. Embedded
    # updater.ps1 + its #Requires manifest are still copied.
    installer_ignore = shutil.ignore_patterns("Tests", "TestResults.xml", "__pycache__")
    for asset in REQUIRED_UPDATER_ASSETS:
        src = PROJECT_ROOT / asset
        if not src.exists():
            raise FileNotFoundError(f"Required updater asset missing: {src}")
        ignore = installer_ignore if asset == "installer" else None
        copy_asset(src, release_dir / asset, ignore=ignore)

    if not args.skip_test and not run_smoke_test(release_dir / f"{APP_NAME}.exe"):
        raise SystemExit(1)

    if args.manifest:
        git_head = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True, text=True,
            cwd=str(PROJECT_ROOT),
        ).stdout.strip()
        write_release_manifest(release_dir, version, f"{APP_NAME}.exe", git_head)
    print(f"[v] DONE: {release_dir.resolve()}")

if __name__ == "__main__":
    main()