import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tomllib
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path

from sky_music.orchestration.native_provenance import native_source_fingerprint


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "pyproject.toml").exists() and (candidate / "Sky-Auto-Player.spec").exists():
            return candidate
    raise RuntimeError("Cannot locate project root. Run build-app from the source checkout.")

PROJECT_ROOT = find_project_root(Path(__file__).resolve())

SPEC_FILE = PROJECT_ROOT / "Sky-Auto-Player.spec"
VERSION_FILE = PROJECT_ROOT / "windows_version_info.txt"
DIST_DIR = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build"

APP_NAME = "Sky-Auto-Player"
NATIVE_CALIBRATION_BINARY = "native_calibration.exe"
REQUIRED_ASSETS = ("config.json", "songs")
REQUIRED_UPDATER_ASSETS = ("updater.bat", "installer")
OPTIONAL_ASSETS = ("README.md",)

VERSION_PY = PROJECT_ROOT / "src" / "sky_music" / "_version.py"
NATIVE_BUILD_PY = PROJECT_ROOT / "src" / "sky_music" / "_native_build.py"

def generate_version_py(version: str) -> None:
    """Write the current version into ``_version.py`` so frozen builds
    have a reliable version string that does not depend on ``importlib.metadata``.
    """
    VERSION_PY.write_text(
        f'# Auto-generated by build_app.py — do not edit manually.\n'
        f'__version__: str = "{version}"\n',
        encoding="utf-8",
    )


def get_git_head(*, require_clean: bool = True) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--verify", "HEAD"],
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
        check=False,
    )
    head = result.stdout.strip()
    if result.returncode != 0 or not head:
        raise RuntimeError("Cannot determine git HEAD for native build provenance")
    dirty_result = subprocess.run(
        ["git", "status", "--porcelain"],
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
        check=False,
    )
    if dirty_result.returncode != 0:
        raise RuntimeError("Cannot determine git worktree state for native build provenance")
    dirty = bool(dirty_result.stdout.strip())
    if dirty and require_clean:
        raise RuntimeError("release build requires a clean Git worktree")
    return f"{head}-dirty" if dirty else head


def generate_native_build_py(
    build_id: str, source_fingerprint: str, *, dirty_worktree: bool = False
) -> None:
    """Embed the exact Rust wheel provenance into frozen Python releases."""
    NATIVE_BUILD_PY.write_text(
        "# Auto-generated by build_app.py — do not edit manually.\n"
        f'EXPECTED_NATIVE_BUILD_ID: str = "{build_id}"\n'
        f'EXPECTED_NATIVE_SOURCE_FINGERPRINT: str = "{source_fingerprint}"\n'
        f'EXPECTED_NATIVE_DIRTY_WORKTREE: bool = {dirty_worktree!r}\n',
        encoding="utf-8",
    )

def get_project_version() -> str:
    path = PROJECT_ROOT / "pyproject.toml"
    try:
        with path.open("rb") as f:
            data = tomllib.load(f)
    except Exception as exc:
        raise RuntimeError(f"Cannot read {path}") from exc

    version = data.get("project", {}).get("version")
    if not isinstance(version, str) or not version.strip():
        raise RuntimeError("Missing or invalid [project].version in pyproject.toml")

    return version.strip()

def windows_version_tuple(version: str) -> tuple[int, int, int, int]:
    parts = [int(x) for x in re.findall(r"\d+", version)[:4]]
    while len(parts) < 4:
        parts.append(0)
    p0, p1, p2, p3 = ([*parts, 0, 0, 0, 0])[:4]
    return (p0, p1, p2, p3)

def generate_version_info(version: str) -> None:
    v_tuple = windows_version_tuple(version)
    v_str = version
    year = datetime.now(UTC).year

    content = f"""
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v_tuple},
    prodvers={v_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'Sky Auto Player Team'),
          StringStruct('FileDescription', 'Sky Auto Player - Music Sheet Player for Windows'),
          StringStruct('FileVersion', '{v_str}'),
          StringStruct('InternalName', '{APP_NAME}'),
          StringStruct('LegalCopyright', 'Copyright (c) {year}'),
          StringStruct('OriginalFilename', '{APP_NAME}.exe'),
          StringStruct('ProductName', 'Sky Auto Player'),
          StringStruct('ProductVersion', '{v_str}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    VERSION_FILE.write_text(content.strip(), encoding="utf-8")

def copy_asset(
    src: Path,
    dst: Path,
    ignore: Callable[[str, list[str]], set[str]] | None = None,
) -> None:
    if dst.exists():
        if dst.is_dir():
            shutil.rmtree(dst)
        else:
            dst.unlink()

    if src.is_dir():
        # `ignore` is a callable returned by shutil.ignore_patterns(...). We
        # use it to exclude the installer/Tests/ subtree and stale
        # TestResults.xml from releases — those are dev-only artifacts and
        # bloat the zip (the Tests/ subtree also leaks machine name / user /
        # OS via the committed TestResults.xml).
        shutil.copytree(src, dst, ignore=ignore)
    else:
        shutil.copy2(src, dst)

def run_smoke_test(exe_path: Path) -> bool:
    exe_path = exe_path.resolve()
    if not exe_path.exists():
        print(f"[!] Missing executable: {exe_path}")
        return False

    # Each smoke step is a thin wrapper around the corresponding ``--selftest-*``
    # branch in ``src/main.py``. Adding a step here also requires wiring the
    # branch in main() and a unit test in ``tests/test_selftest_*.py``.
    smoke_steps = [
        (
            "--selftest-textual",
            "Textual picker headless mount + rapidfuzz import",
        ),
        (
            "--selftest-optimize",
            "frozen build optimization contract (assert strips at optimize>=1)",
        ),
        (
            "--selftest-rust",
            "native Rust module import + mock dispatch worker",
        ),
    ]
    for flag, description in smoke_steps:
        print(f"[+] Running Smoke Test: {exe_path} {flag}  ({description})")
        try:
            result = subprocess.run(
                [str(exe_path), flag],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=str(exe_path.parent),
            )
        except Exception as exc:
            print(f"[!] Error while running Smoke Test ({flag}): {exc}")
            return False

        if result.returncode != 0:
            print(f"[!] Smoke Test FAILED for {flag} (rc={result.returncode}).")
            print(result.stderr or result.stdout)
            return False

    print("[v] Smoke Test SUCCEEDED.")
    return True


def run_native_calibration_smoke_test(binary_path: Path) -> bool:
    """Verify the isolated calibration process starts without registering input."""
    binary_path = binary_path.resolve()
    if not binary_path.is_file():
        print(f"[!] Missing native calibration binary: {binary_path}")
        return False
    try:
        result = subprocess.run(
            [str(binary_path), "--help"],
            capture_output=True,
            text=True,
            check=False,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        print(f"[!] Native calibration --help smoke test failed: {exc}")
        return False
    if result.returncode != 0 or not result.stdout.strip():
        print(
            "[!] Native calibration --help smoke test returned "
            f"{result.returncode}: {result.stderr.strip()}"
        )
        return False
    return True


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def write_release_manifest(
    release_dir: Path,
    version: str,
    exe_name: str,
    git_head: str,
    *,
    dirty_worktree: bool = False,
    native_build_commit: str | None = None,
    native_source_fingerprint: str | None = None,
) -> None:
    smoke_log = release_dir / "_smoke_test.log"
    try:
        smoke_log.unlink(missing_ok=True)
    except OSError as exc:
        raise RuntimeError(f"Failed to remove temporary smoke-test log: {smoke_log}") from exc

    executable = release_dir / exe_name
    if not executable.is_file():
        raise RuntimeError(f"Release executable is missing: {executable}")

    exclude = {exe_name, "MANIFEST.json"}
    files: list[dict[str, str | int]] = []
    for path in sorted(release_dir.rglob("*")):
        if not path.is_file():
            continue
        try:
            relative = path.relative_to(release_dir).as_posix()
            if relative in exclude:
                continue
            size = path.stat().st_size
            sha256 = _hash_file(path)
        except (OSError, ValueError) as exc:
            raise RuntimeError(f"Failed to hash release asset: {path}") from exc
        files.append({"path": relative, "size": size, "sha256": sha256})

    try:
        executable_sha256 = _hash_file(executable)
    except OSError as exc:
        raise RuntimeError(f"Failed to hash release executable: {executable}") from exc

    manifest = {
        "app": APP_NAME,
        "version": version,
        "executable": exe_name,
        "executable_sha256": executable_sha256,
        "interpreter": {
            "implementation": sys.implementation.name,
            "version": sys.version.split()[0],
            "freethreaded": not sys._is_gil_enabled(),
        },
        "platform": sys.platform,
        "git_head": git_head,
        "dirty_worktree": dirty_worktree,
        "native_build_commit": git_head if native_build_commit is None else native_build_commit,
        "native_source_fingerprint": native_source_fingerprint,
        # Emit RFC-3339 UTC with explicit Z suffix.
        "build_time_utc": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "files": files,
    }
    out = release_dir / "MANIFEST.json"
    out.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"[+] Manifest: {release_dir.name}/{out.name}")


def kill_hanging_selftest(release_dir: Path) -> None:
    """Attempt to force kill any lingering smoke test processes from our specific release dir."""
    if not release_dir.exists():
        return

    release_root = str(release_dir.resolve()).replace("'", "''")
    ps = f"""
    Get-CimInstance Win32_Process |
      Where-Object {{
        $_.Name -eq '{APP_NAME}.exe' -and
        $_.ExecutablePath -like '{release_root}\\*'
      }} |
      ForEach-Object {{
        Stop-Process -Id $_.ProcessId -Force
      }}
    """
    try:
        subprocess.run(
            ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps],
            capture_output=True,
            text=True,
        )
        import time
        time.sleep(1) # Give OS time to release file handles
    except Exception:
        pass


def main() -> None:
    if sys.platform != "win32":
        raise SystemExit("[!] Error: This project only supports building on Windows.")

    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-test", action="store_true")
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Reuse PyInstaller analysis cache for inner-loop. "
             "Never use for release builds.",
    )
    parser.add_argument(
        "--manifest",
        action="store_true",
        help="Generate MANIFEST.json with SHA256 hashes for every "
             "file in the release directory.",
    )
    args = parser.parse_args()

    version = get_project_version()
    print(f"=== Sky Auto Player Build Pipeline v{version} ===")

    git_head = get_git_head()
    native_fingerprint = native_source_fingerprint(PROJECT_ROOT, "cp314t-win_amd64")
    generate_version_py(version)
    generate_native_build_py(
        git_head,
        native_fingerprint,
        dirty_worktree=False,
    )
    generate_version_info(version)

    release_dir = DIST_DIR / f"{APP_NAME}-v{version}"
    kill_hanging_selftest(release_dir)

    if not args.no_clean and BUILD_DIR.exists():
        try:
            shutil.rmtree(BUILD_DIR)
        except PermissionError as e:
            print(f"[!] Error cleaning BUILD_DIR: {e}. Attempting to continue...")

    if not args.no_clean and DIST_DIR.exists():
        try:
            shutil.rmtree(DIST_DIR)
        except PermissionError as e:
            raise SystemExit(f"[!] Error cleaning DIST_DIR: {e}.\nFix: close any CMD/Explorer windows currently open in {DIST_DIR} and try again.") from e

    rust_dir = PROJECT_ROOT / "rust"
    if rust_dir.exists():
        print("[+] Rust workspace detected. Running Rust wheel precheck...")
        build_script = PROJECT_ROOT / "scripts" / "build_rust_wheel.py"
        subprocess.run(
            [sys.executable, str(build_script)],
            check=True,
            cwd=str(PROJECT_ROOT),
        )
        calibration_manifest = rust_dir / "crates" / "sky_dispatch_win32" / "Cargo.toml"
        print("[+] Building the process-isolated native calibration binary...")
        native_build_commit = git_head
        native_build_env = os.environ.copy()
        native_build_env["GITHUB_SHA"] = native_build_commit
        native_build_env["SKY_NATIVE_BUILD_COMMIT"] = native_build_commit
        native_build_env["SKY_NATIVE_SOURCE_FINGERPRINT"] = native_fingerprint
        native_build_env["SKY_NATIVE_DIRTY_WORKTREE"] = "false"
        subprocess.run(
            [
                "cargo",
                "build",
                "--manifest-path",
                str(calibration_manifest),
                "--bin",
                "native_calibration",
                "--release",
            ],
            check=True,
            cwd=str(PROJECT_ROOT),
            env=native_build_env,
        )

    print("[+] Starting PyInstaller...")
    clean_flag = [] if args.no_clean else ["--clean"]
    subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--noconfirm", *clean_flag, str(SPEC_FILE)],
        check=True,
        cwd=str(PROJECT_ROOT),
    )

    raw_dist = DIST_DIR / APP_NAME

    if not raw_dist.exists():
        raise RuntimeError(f"PyInstaller output missing: {raw_dist}")

    print(f"[+] Moving artifact to {release_dir.name}...")
    if release_dir.exists():
        shutil.rmtree(release_dir)
    shutil.move(str(raw_dist), str(release_dir))

    calibration_binary = rust_dir / "target" / "release" / NATIVE_CALIBRATION_BINARY
    if not calibration_binary.is_file():
        raise RuntimeError(f"Native calibration binary is missing: {calibration_binary}")
    copy_asset(calibration_binary, release_dir / NATIVE_CALIBRATION_BINARY)
    if not run_native_calibration_smoke_test(release_dir / NATIVE_CALIBRATION_BINARY):
        raise RuntimeError("Native calibration binary smoke test failed")

    print("[+] Copying assets...")
    for asset in REQUIRED_ASSETS:
        src = PROJECT_ROOT / asset
        if not src.exists():
            raise FileNotFoundError(f"Required asset missing: {src}")
        copy_asset(src, release_dir / asset)

    for asset in OPTIONAL_ASSETS:
        src = PROJECT_ROOT / asset
        if src.exists():
            copy_asset(src, release_dir / asset)

    print("[+] Copying updater assets...")
    # Exclude dev-only artifacts from the installer/ tree shipped with the
    # release: the Pester Tests/ subtree and stale TestResults.xml bloat the
    # zip and leak the previous build's machine/user identifiers. Embedded
    # updater.ps1 + its #Requires manifest are still copied.
    installer_ignore = shutil.ignore_patterns("Tests", "TestResults.xml", "__pycache__")
    for asset in REQUIRED_UPDATER_ASSETS:
        src = PROJECT_ROOT / asset
        if not src.exists():
            raise FileNotFoundError(f"Required updater asset missing: {src}")
        ignore = installer_ignore if asset == "installer" else None
        copy_asset(src, release_dir / asset, ignore=ignore)

    if not args.skip_test and not run_smoke_test(release_dir / f"{APP_NAME}.exe"):
        raise SystemExit(1)

    if args.manifest:
        write_release_manifest(
            release_dir,
            version,
            f"{APP_NAME}.exe",
            git_head,
            dirty_worktree=False,
            native_build_commit=git_head,
            native_source_fingerprint=native_fingerprint,
        )

    print(f"[v] DONE: {release_dir.resolve()}")

if __name__ == "__main__":
    main()
