import argparse
import contextlib
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tomllib
from collections.abc import Callable
from datetime import UTC, datetime
from functools import wraps
from pathlib import Path

from sky_music.orchestration.native_admission import EXPECTED_NATIVE_ABI
from sky_music.orchestration.native_models import RUST_DISPATCH_SCHEMA_VERSION


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "pyproject.toml").exists() and (candidate / "Sky-Auto-Player.spec").exists():
            return candidate
    raise RuntimeError("Cannot locate project root. Run build-app from the source checkout.")

PROJECT_ROOT = find_project_root(Path(__file__).resolve())

SPEC_FILE = PROJECT_ROOT / "Sky-Auto-Player.spec"
VERSION_FILE = PROJECT_ROOT / "windows_version_info.txt"
DIST_DIR = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build"

APP_NAME = "Sky-Auto-Player"
NATIVE_CALIBRATION_BINARY = "native_calibration.exe"
NATIVE_UPDATER_BINARY = "Sky-Auto-Player-Updater.exe"
REQUIRED_ASSETS = ("config.json", "songs")
OPTIONAL_ASSETS = ("README.md",)
RUST_TOOLCHAIN_FILE = PROJECT_ROOT / "rust" / "rust-toolchain.toml"

VERSION_PY = PROJECT_ROOT / "src" / "sky_music" / "_version.py"
NATIVE_BUILD_PY = PROJECT_ROOT / "src" / "sky_music" / "_native_build.py"


def get_pinned_rust_toolchain() -> str:
    """Read and validate the exact Rust channel used by native builds."""
    try:
        with RUST_TOOLCHAIN_FILE.open("rb") as source:
            data = tomllib.load(source)
    except OSError as exc:
        raise RuntimeError(f"Cannot read Rust toolchain file: {RUST_TOOLCHAIN_FILE}") from exc

    channel = data.get("toolchain", {}).get("channel")
    if not isinstance(channel, str) or re.fullmatch(r"\d+\.\d+\.\d+", channel) is None:
        raise RuntimeError(
            f"Rust toolchain file must pin an exact x.y.z channel: {RUST_TOOLCHAIN_FILE}"
        )
    return channel


def expected_rustc_version_prefix() -> str:
    return f"rustc {get_pinned_rust_toolchain()} "


def native_build_environment() -> dict[str, str]:
    env = os.environ.copy()
    env["RUSTUP_TOOLCHAIN"] = get_pinned_rust_toolchain()
    return env


def cargo_release_build_command(manifest: Path, binary: str) -> list[str]:
    """Return the locked Cargo command for a shipped native binary.

    The historical function name is retained for callers and tests. Release
    packaging now uses the explicit ``dist`` profile so an engineering profile
    change cannot silently affect distributed binaries.
    """
    return [
        "cargo",
        "build",
        "--manifest-path",
        str(manifest),
        "--bin",
        binary,
        "--profile",
        "dist",
        "--locked",
    ]

def generate_version_py(version: str) -> None:
    """Write the current version into ``_version.py`` so frozen builds
    have a reliable version string that does not depend on ``importlib.metadata``.
    """
    VERSION_PY.write_text(
        f'# Auto-generated by build_app.py — do not edit manually.\n'
        f'__version__: str = "{version}"\n',
        encoding="utf-8",
    )


def get_git_head(*, require_clean: bool = True) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--verify", "HEAD"],
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
        check=False,
    )
    head = result.stdout.strip()
    if result.returncode != 0 or not head:
        raise RuntimeError("Cannot determine git HEAD for native build provenance")
    dirty_result = subprocess.run(
        ["git", "status", "--porcelain"],
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
        check=False,
    )
    if dirty_result.returncode != 0:
        raise RuntimeError("Cannot determine git worktree state for native build provenance")
    dirty = bool(dirty_result.stdout.strip())
    if dirty and require_clean:
        raise RuntimeError("release build requires a clean Git worktree")
    return f"{head}-dirty" if dirty else head


def generate_native_build_py(
    app_commit: str,
) -> None:
    """Embed the exact application commit into the frozen Python release."""
    NATIVE_BUILD_PY.write_text(
        "# Auto-generated by build_app.py — do not edit manually.\n"
        f'APP_BUILD_COMMIT: str = "{app_commit}"\n',
        encoding="utf-8",
    )


def _restore_native_build_metadata_after_build[**P, R](
    func: Callable[P, R],
) -> Callable[P, R]:
    """Restore ignored release metadata after success or a failed build."""

    @wraps(func)
    def wrapped(*args: P.args, **kwargs: P.kwargs) -> R:
        metadata_existed = NATIVE_BUILD_PY.exists()
        previous_content = NATIVE_BUILD_PY.read_bytes() if metadata_existed else None
        try:
            return func(*args, **kwargs)
        finally:
            if metadata_existed and previous_content is not None:
                NATIVE_BUILD_PY.write_bytes(previous_content)
            else:
                NATIVE_BUILD_PY.unlink(missing_ok=True)

    return wrapped


def verify_native_build_info(expected_commit: str) -> None:
    """Verify the wheel installed by the application build pipeline."""

    import sky_player_rs  # type: ignore[import-not-found]

    info = dict(sky_player_rs.build_info())  # type: ignore[attr-defined]
    checks = {
        "native_build_commit": expected_commit,
        "native_abi": EXPECTED_NATIVE_ABI,
        "schema_version": RUST_DISPATCH_SCHEMA_VERSION,
        "native_schema_version": RUST_DISPATCH_SCHEMA_VERSION,
        "free_threaded": True,
        "win32_backend": True,
    }
    for field, expected in checks.items():
        if info.get(field) != expected:
            raise RuntimeError(
                f"native build metadata mismatch for {field}: "
                f"expected {expected!r}, actual {info.get(field)!r}"
            )
    rustc_version = info.get("rustc_version")
    expected_prefix = expected_rustc_version_prefix()
    if not isinstance(rustc_version, str) or not rustc_version.startswith(expected_prefix):
        raise RuntimeError(
            "native build metadata mismatch for rustc_version: "
            f"expected prefix {expected_prefix!r}, actual {rustc_version!r}"
        )

def get_project_version() -> str:
    path = PROJECT_ROOT / "pyproject.toml"
    try:
        with path.open("rb") as f:
            data = tomllib.load(f)
    except Exception as exc:
        raise RuntimeError(f"Cannot read {path}") from exc

    version = data.get("project", {}).get("version")
    if not isinstance(version, str) or not version.strip():
        raise RuntimeError("Missing or invalid [project].version in pyproject.toml")

    return version.strip()

def windows_version_tuple(version: str) -> tuple[int, int, int, int]:
    parts = [int(x) for x in re.findall(r"\d+", version)[:4]]
    while len(parts) < 4:
        parts.append(0)
    p0, p1, p2, p3 = ([*parts, 0, 0, 0, 0])[:4]
    return (p0, p1, p2, p3)

def generate_version_info(version: str) -> None:
    v_tuple = windows_version_tuple(version)
    v_str = version
    year = datetime.now(UTC).year

    content = f"""
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v_tuple},
    prodvers={v_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'Sky Auto Player Team'),
          StringStruct('FileDescription', 'Sky Auto Player - Music Sheet Player for Windows'),
          StringStruct('FileVersion', '{v_str}'),
          StringStruct('InternalName', '{APP_NAME}'),
          StringStruct('LegalCopyright', 'Copyright (c) {year}'),
          StringStruct('OriginalFilename', '{APP_NAME}.exe'),
          StringStruct('ProductName', 'Sky Auto Player'),
          StringStruct('ProductVersion', '{v_str}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    VERSION_FILE.write_text(content.strip(), encoding="utf-8")

def copy_asset(
    src: Path,
    dst: Path,
    ignore: Callable[[str, list[str]], set[str]] | None = None,
) -> None:
    if dst.exists():
        if dst.is_dir():
            shutil.rmtree(dst)
        else:
            dst.unlink()

    if src.is_dir():
        # Keep the helper generic for directory assets; release contents are
        # asserted separately by verify_release_manifest.py.
        shutil.copytree(src, dst, ignore=ignore)
    else:
        shutil.copy2(src, dst)

def run_smoke_test(exe_path: Path) -> bool:
    exe_path = exe_path.resolve()
    if not exe_path.exists():
        print(f"[!] Missing executable: {exe_path}")
        return False

    # Each smoke step is a thin wrapper around the corresponding ``--selftest-*``
    # branch in ``src/main.py``. Adding a step here also requires wiring the
    # branch in main() and a unit test in ``tests/test_selftest_*.py``.
    smoke_steps = [
        (
            "--selftest-textual",
            "Textual picker headless mount + rapidfuzz import",
        ),
        (
            "--selftest-optimize",
            "frozen build optimization contract (assert strips at optimize>=1)",
        ),
        (
            "--selftest-rust",
            "native Rust module import + mock dispatch worker",
        ),
    ]
    for flag, description in smoke_steps:
        print(f"[+] Running Smoke Test: {exe_path} {flag}  ({description})")
        try:
            result = subprocess.run(
                [str(exe_path), flag],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=str(exe_path.parent),
            )
        except Exception as exc:
            print(f"[!] Error while running Smoke Test ({flag}): {exc}")
            return False

        if result.returncode != 0:
            print(f"[!] Smoke Test FAILED for {flag} (rc={result.returncode}).")
            print(result.stderr or result.stdout)
            return False

    print("[v] Smoke Test SUCCEEDED.")
    return True


def run_native_calibration_smoke_test(binary_path: Path) -> bool:
    """Verify the isolated calibration process starts without registering input."""
    binary_path = binary_path.resolve()
    if not binary_path.is_file():
        print(f"[!] Missing native calibration binary: {binary_path}")
        return False
    try:
        result = subprocess.run(
            [str(binary_path), "--help"],
            capture_output=True,
            text=True,
            check=False,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        print(f"[!] Native calibration --help smoke test failed: {exc}")
        return False
    if result.returncode != 0 or not result.stdout.strip():
        print(
            "[!] Native calibration --help smoke test returned "
            f"{result.returncode}: {result.stderr.strip()}"
        )
        return False
    return True


@contextlib.contextmanager
def _source_bootloader_override():
    """Temporarily make PyInstaller use the verified source-built bootloader."""

    source_dir_value = os.environ.get("SKY_SOURCE_BOOTLOADER_DIR", "")
    required = os.environ.get("SKY_REQUIRE_SOURCE_BOOTLOADER") == "1"
    if not source_dir_value:
        if required:
            raise RuntimeError(
                "release build requires SKY_SOURCE_BOOTLOADER_DIR from the source-build gate"
            )
        yield
        return
    source_dir = Path(source_dir_value).resolve()
    source = source_dir / "run.exe"
    metadata_path = source_dir / "metadata.json"
    if not source.is_file() or not metadata_path.is_file():
        raise RuntimeError(f"source-built PyInstaller bootloader is incomplete: {source_dir}")
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError("source-built PyInstaller bootloader metadata is invalid") from exc
    if not isinstance(metadata, dict) or metadata.get("sha256") != _hash_file(source):
        raise RuntimeError("source-built PyInstaller bootloader metadata hash mismatch")

    import PyInstaller

    if metadata.get("pyinstaller_version") != PyInstaller.__version__:
        raise RuntimeError("source-built bootloader version does not match PyInstaller")

    installed = (
        Path(PyInstaller.__file__).resolve().parent
        / "bootloader"
        / PyInstaller.PLATFORM
        / "run.exe"
    )
    if not installed.is_file():
        raise RuntimeError(f"installed PyInstaller bootloader is missing: {installed}")
    backup = installed.read_bytes()
    shutil.copy2(source, installed)
    try:
        yield
    finally:
        installed.write_bytes(backup)


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def write_release_manifest(
    release_dir: Path,
    version: str,
    exe_name: str,
    git_head: str,
    *,
    dirty_worktree: bool = False,
    native_build_commit: str | None = None,
) -> None:
    smoke_log = release_dir / "_smoke_test.log"
    try:
        smoke_log.unlink(missing_ok=True)
    except OSError as exc:
        raise RuntimeError(f"Failed to remove temporary smoke-test log: {smoke_log}") from exc

    executable = release_dir / exe_name
    if not executable.is_file():
        raise RuntimeError(f"Release executable is missing: {executable}")

    exclude = {"MANIFEST.json"}
    files: list[dict[str, str | int]] = []
    for path in sorted(release_dir.rglob("*")):
        if not path.is_file():
            continue
        try:
            relative = path.relative_to(release_dir).as_posix()
            if relative in exclude:
                continue
            size = path.stat().st_size
            sha256 = _hash_file(path)
        except (OSError, ValueError) as exc:
            raise RuntimeError(f"Failed to hash release asset: {path}") from exc
        files.append({"path": relative, "size": size, "sha256": sha256})

    manifest = {
        "schema_version": 2,
        "app": APP_NAME,
        "version": version,
        "executable": exe_name,
        "git_head": git_head,
        "dirty_worktree": dirty_worktree,
        "native_build_commit": git_head if native_build_commit is None else native_build_commit,
        # Emit RFC-3339 UTC with explicit Z suffix.
        "build_time_utc": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "files": files,
    }
    out = release_dir / "MANIFEST.json"
    out.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"[+] Manifest: {release_dir.name}/{out.name}")


@_restore_native_build_metadata_after_build
def main() -> None:
    if sys.platform != "win32":
        raise SystemExit("[!] Error: This project only supports building on Windows.")

    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-test", action="store_true")
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Reuse PyInstaller analysis cache for inner-loop. "
             "Never use for release builds.",
    )
    parser.add_argument(
        "--manifest",
        action="store_true",
        help="Generate MANIFEST.json with SHA256 hashes for every "
             "file in the release directory.",
    )
    parser.add_argument(
        "--manifest-only",
        action="store_true",
        help="Hash an already-built unsigned release directory without rebuilding.",
    )
    parser.add_argument(
        "--release-dir",
        type=Path,
        help="Existing release directory for --manifest-only (defaults to dist/<name>-v<version>).",
    )
    args = parser.parse_args()

    version = get_project_version()
    print(f"=== Sky Auto Player Build Pipeline v{version} ===")

    if args.manifest_only:
        release_dir = (
            args.release_dir.resolve()
            if args.release_dir is not None
            else DIST_DIR / f"{APP_NAME}-v{version}"
        )
        if not release_dir.is_dir():
            raise RuntimeError(f"release directory is missing: {release_dir}")
        git_head = get_git_head()
        write_release_manifest(
            release_dir,
            version,
            f"{APP_NAME}.exe",
            git_head,
            dirty_worktree=False,
            native_build_commit=git_head,
        )
        print(f"[v] Manifest-only DONE: {release_dir.resolve()}")
        return

    git_head = get_git_head()
    generate_version_py(version)
    generate_native_build_py(git_head)
    generate_version_info(version)

    release_dir = DIST_DIR / f"{APP_NAME}-v{version}"
    if not args.no_clean and BUILD_DIR.exists():
        try:
            shutil.rmtree(BUILD_DIR)
        except PermissionError as e:
            print(f"[!] Error cleaning BUILD_DIR: {e}. Attempting to continue...")

    if not args.no_clean and DIST_DIR.exists():
        try:
            shutil.rmtree(DIST_DIR)
        except PermissionError as e:
            raise SystemExit(f"[!] Error cleaning DIST_DIR: {e}.\nFix: close any CMD/Explorer windows currently open in {DIST_DIR} and try again.") from e

    rust_dir = PROJECT_ROOT / "rust"
    if rust_dir.exists():
        print("[+] Rust workspace detected. Running Rust wheel precheck...")
        build_script = PROJECT_ROOT / "scripts" / "build_rust_wheel.py"
        native_build_env = native_build_environment()
        subprocess.run(
            [sys.executable, str(build_script), "--profile", "dist"],
            check=True,
            cwd=str(PROJECT_ROOT),
            env=native_build_env,
        )
        verify_native_build_info(git_head)
        calibration_manifest = rust_dir / "crates" / "sky_dispatch_win32" / "Cargo.toml"
        print("[+] Building the process-isolated native calibration binary...")
        native_build_commit = git_head
        native_build_env["GITHUB_SHA"] = native_build_commit
        native_build_env["SKY_NATIVE_BUILD_COMMIT"] = native_build_commit
        from sky_music.orchestration.native_provenance import native_source_fingerprint

        native_build_env["SKY_NATIVE_SOURCE_FINGERPRINT"] = native_source_fingerprint(
            PROJECT_ROOT, "cp314t-win_amd64"
        )
        native_build_env["SKY_NATIVE_DIRTY_WORKTREE"] = "false"
        subprocess.run(
            cargo_release_build_command(calibration_manifest, "native_calibration"),
            check=True,
            cwd=str(PROJECT_ROOT),
            env=native_build_env,
        )
        updater_manifest = rust_dir / "crates" / "sky_updater" / "Cargo.toml"
        print("[+] Building the native self-updater...")
        subprocess.run(
            cargo_release_build_command(updater_manifest, "sky_updater"),
            check=True,
            cwd=str(PROJECT_ROOT),
            env=native_build_env,
        )
    print("[+] Starting PyInstaller...")
    clean_flag = [] if args.no_clean else ["--clean"]
    with _source_bootloader_override():
        subprocess.run(
            [sys.executable, "-m", "PyInstaller", "--noconfirm", *clean_flag, str(SPEC_FILE)],
            check=True,
            cwd=str(PROJECT_ROOT),
        )

    raw_dist = DIST_DIR / APP_NAME

    if not raw_dist.exists():
        raise RuntimeError(f"PyInstaller output missing: {raw_dist}")

    print(f"[+] Moving artifact to {release_dir.name}...")
    if release_dir.exists():
        shutil.rmtree(release_dir)
    shutil.move(str(raw_dist), str(release_dir))

    calibration_binary = rust_dir / "target" / "dist" / NATIVE_CALIBRATION_BINARY
    if not calibration_binary.is_file():
        raise RuntimeError(f"Native calibration binary is missing: {calibration_binary}")
    copy_asset(calibration_binary, release_dir / NATIVE_CALIBRATION_BINARY)
    if not run_native_calibration_smoke_test(release_dir / NATIVE_CALIBRATION_BINARY):
        raise RuntimeError("Native calibration binary smoke test failed")

    updater_binary = rust_dir / "target" / "dist" / "sky_updater.exe"
    if not updater_binary.is_file():
        raise RuntimeError(f"Native updater binary is missing: {updater_binary}")
    copy_asset(updater_binary, release_dir / NATIVE_UPDATER_BINARY)

    print("[+] Copying assets...")
    for asset in REQUIRED_ASSETS:
        src = PROJECT_ROOT / asset
        if not src.exists():
            raise FileNotFoundError(f"Required asset missing: {src}")
        copy_asset(src, release_dir / asset)

    for asset in OPTIONAL_ASSETS:
        src = PROJECT_ROOT / asset
        if src.exists():
            copy_asset(src, release_dir / asset)

    if not args.skip_test and not run_smoke_test(release_dir / f"{APP_NAME}.exe"):
        raise SystemExit(1)

    if args.manifest:
        write_release_manifest(
            release_dir,
            version,
            f"{APP_NAME}.exe",
            git_head,
            dirty_worktree=False,
            native_build_commit=git_head,
        )

    print(f"[v] DONE: {release_dir.resolve()}")

if __name__ == "__main__":
    main()
